baseURL = "http://localhost/"
languageCode = "en-us"
title = "This Adds Up"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"


[pagination]
  pagerSize = 10

[params]
  env = "production"
  title = "This Adds Up"
  description = "Smart tools for solving everyday math and money mysteries."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
